import time
from datetime import datetime, time as dt_time
from zoneinfo import ZoneInfo

from src.live_trade_monitor import run_monitor
from src.market_scanner import print_results, scan_market, select_best_candidate
from src.risk_manager import can_open_new_trade, is_entry_window, now_ist
from src.telegram_alert import send_entry_alert
from src.trade_engine import create_trade, resolve_option_contract
from src.options_engine_adapter import evaluate_option_candidate
from src.high_conviction_discovery import discover
from src.upgrade_config import RESCAN_DELAY_SECONDS, MINIMUM_SCORE, MAX_TRADES_PER_DAY, MAX_DAILY_LOSS, OPTIONS_MIN_SCORE

CAPITAL = 50000


def wait_for_0915_ist():
    tz = ZoneInfo("Asia/Kolkata")
    start = dt_time(9, 15)
    while True:
        now = datetime.now(tz)
        if now.time() >= start:
            print("09:15 IST reached — starting PRO multi-timeframe live-data scan.")
            return
        target = now.replace(hour=9, minute=15, second=0, microsecond=0)
        time.sleep(min(max(1, int((target - now).total_seconds())), 60))


def main():
    wait_for_0915_ist()
    print("=" * 72)
    print("PEREZ AI PAPER-TRADING BOT — PRO MTF PIPELINE")
    print("Paper mode only — no real orders are placed.")
    print("Decision frames: 5m execution + 15m confirmation + 60m regime")
    print(f"Market score threshold: {MINIMUM_SCORE} | Options threshold: {OPTIONS_MIN_SCORE}")
    print(f"Rescan interval: {RESCAN_DELAY_SECONDS}s")
    print("=" * 72)

    while True:
        if not is_entry_window():
            current = now_ist()
            print(f"Waiting — outside entry window: {current.strftime('%H:%M:%S')} IST | entry window 09:30-14:45 IST")
            time.sleep(RESCAN_DELAY_SECONDS)
            continue

        allowed, reason, summary = can_open_new_trade(MAX_TRADES_PER_DAY, MAX_DAILY_LOSS, CAPITAL)
        print(f"Today's closed trades: {summary['closed_trades']} | Today's P/L: Rs {summary['pnl']:.2f}")
        if not allowed:
            print(f"Trading paused by risk gate: {reason}")
            time.sleep(RESCAN_DELAY_SECONDS)
            continue

        results = scan_market()
        print_results(results)
        admitted, rejected = discover()
        print(f"Fundamental candidates admitted: {len(admitted)} | rejected: {len(rejected)}")
        if not admitted:
            print("No HIGH-CONVICTION fundamental candidate. No paper trade will be created.")
            time.sleep(RESCAN_DELAY_SECONDS)
            continue

        admitted_symbols = {x["symbol"].upper() for x in admitted}
        eligible_market = [x for x in results if x.get("symbol", "").upper() in admitted_symbols]
        candidate = select_best_candidate(eligible_market, MINIMUM_SCORE)
        if not candidate:
            print("Fundamental candidate exists, but no PRO multi-timeframe market signal passed.")
            time.sleep(RESCAN_DELAY_SECONDS)
            continue

        tf_scores = candidate.get("timeframe_scores", {})
        tf_dirs = candidate.get("timeframe_directions", {})
        print(f"PRO CANDIDATE: {candidate['symbol']} | Score={candidate['score']}/100 | 5m/15m/60m={tf_scores.get('5m', 0):.1f}/{tf_scores.get('15m', 0):.1f}/{tf_scores.get('60m', 0):.1f} | {tf_dirs}")

        signal = candidate["signal"]
        option_type = "CE" if signal == "BUY CE" else "PE"
        contract_probe = resolve_option_contract(candidate["symbol"], candidate["close"], signal)
        if contract_probe.get("status") != "CONTRACT VALID":
            print("Options contract/LTP validation rejected candidate:", contract_probe)
            time.sleep(RESCAN_DELAY_SECONDS)
            continue

        # Only use evidence genuinely generated by the PRO scanner. External
        # OI/IV/news/Greeks remain zero until a trusted live source supplies it.
        gate_candidate = {
            "symbol": candidate["symbol"], "option_type": option_type,
            "expiry": contract_probe.get("expiry", ""), "ltp": contract_probe.get("ltp", 0),
            "exchange": contract_probe.get("exchange", "NFO"), "token": contract_probe.get("token", ""),
            "trend_score": tf_scores.get("60m", candidate["score"]),
            "momentum_score": tf_scores.get("5m", candidate["score"]),
            "volume_score": min(100.0, max(0.0, candidate.get("volume_ratio", 0.0) * 50.0)),
            "vwap_score": 100.0 if candidate.get("close", 0) > candidate.get("vwap", 0) else 0.0,
            "index_confirmation": 100.0 if tf_dirs.get("15m") == signal else 0.0,
            "structure_score": 100.0 if candidate.get("structure") in ("BULL_BREAKOUT", "BEAR_BREAKDOWN") else 60.0,
            "volatility_score": min(100.0, max(0.0, candidate.get("atr", 0.0) / max(candidate.get("close", 1.0), 1.0) * 5000.0)),
            "oi_score": 0, "oi_change_score": 0, "iv_score": 0, "liquidity_score": 0,
            "news_confirmation": 0, "event_risk_penalty": 0, "spread_pct": 0, "slippage_pct": 0,
        }
        options_result = evaluate_option_candidate(gate_candidate)
        gate = options_result.get("options_gate", {})
        print(f"OPTIONS GATE: {options_result.get('options_score', 0)}/100 | {gate.get('decision', 'NO TRADE')}")
        if not options_result.get("paper_trade_candidate") or options_result.get("options_score", 0) < OPTIONS_MIN_SCORE:
            print("Options gate rejected candidate:", gate.get("reasons", []))
            time.sleep(RESCAN_DELAY_SECONDS)
            continue

        trade = create_trade(candidate["symbol"], candidate["close"], signal, CAPITAL)
        if trade.get("status") != "PAPER TRADE ACTIVE":
            print("Trade was not created:", trade)
            time.sleep(RESCAN_DELAY_SECONDS)
            continue

        # Preserve the complete PRO decision context through the monitor/logging lifecycle.
        trade["pro_score"] = candidate["score"]
        trade["timeframe_scores"] = tf_scores
        trade["timeframe_directions"] = tf_dirs
        trade["pro_reasons"] = candidate.get("reasons", [])
        trade["data_quality"] = candidate.get("data_quality", False)
        trade["options_score"] = options_result.get("options_score", 0)
        trade["live_orders"] = False

        send_entry_alert(trade)
        result = run_monitor(trade)
        if result is None:
            print("Bot stopped manually.")
            return
        print("Trade cycle complete. Returning to scanner.")
        time.sleep(RESCAN_DELAY_SECONDS)


if __name__ == "__main__":
    main()
