(function(){
'use strict';
const q=id=>document.getElementById(id);
function esc(v){return String(v??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function pct(v){return v==null?'—':Number(v).toFixed(1)+'%';}
function age(ts){if(!ts)return '—'; const t=Date.parse(String(ts).replace(' ','T')); if(!Number.isFinite(t))return '—'; const s=Math.max(0,(Date.now()-t)/1000); return s<60?s.toFixed(1)+'s ago':Math.floor(s/60)+'m ago';}
function latency(ts){if(!ts)return null; const t=Date.parse(String(ts).replace(' ','T')); if(!Number.isFinite(t))return null; return Math.max(0,(Date.now()-t)/1000);}
function inject(){
 if(q('advancedCenter'))return;
 const grid=document.querySelector('.grid'); if(!grid)return;
 const wrap=document.createElement('div'); wrap.id='advancedCenter'; wrap.className='card full';
 wrap.innerHTML=`<div class="h">⚡ ADVANCED LIVE INTELLIGENCE</div>
 <div class="advhero"><div><div class="advtag">🔥 HIGH-VALUE TRADE SUGGESTION</div><div id="hvTitle" class="advtitle">Waiting for live evidence…</div><div id="hvMeta" class="muted">No qualifying event yet</div></div><div id="hvScore" class="advscore">—</div></div>
 <div id="hvWhy" class="advwhy">PEREZ will classify high-value opportunities from live event evidence. This never bypasses risk or option gates.</div>
 <div class="advgrid"><div class="advmetric"><b id="liveSurges">0</b><span>LIVE SURGES</span></div><div class="advmetric"><b id="avgCatch">—</b><span>AVG CATCH</span></div><div class="advmetric"><b id="bestCatch">—</b><span>FASTEST</span></div><div class="advmetric"><b id="hvCount">0</b><span>HIGH VALUE</span></div></div>
 <div class="h" style="margin-top:12px">📡 LIVE SURGE EVENTS <span id="surgeClock" class="muted"></span></div><div id="liveFeed" class="livefeed"></div>
 <div class="h" style="margin-top:12px">🎛️ QUICK INTERPRETATION</div><div class="controls"><button class="btn" data-adv="BULLISH_CE">🟢 BULLISH / CE</button><button class="btn" data-adv="BEARISH_PE">🔴 BEARISH / PE</button><button class="btn" data-adv="WAIT">⏳ WAIT</button><button class="btn" data-adv="NO_TRADE">🚫 NO TRADE</button><button class="btn" data-adv="WATCH">👀 WATCH</button><button class="btn" data-adv="TRAP">🪤 TRAP</button><button class="btn" data-adv="MOMENTUM_CONFIRMED">⚡ MOMENTUM CONFIRMED</button><button class="btn" data-adv="REVERSAL_LIKELY">🔄 REVERSAL LIKELY</button><button class="btn" data-adv="EXPLOSIVE_MOVE">💥 EXPLOSIVE</button><button class="btn" data-adv="MOMENTUM_EXHAUSTED">🧯 EXHAUSTED</button></div>`;
 grid.insertBefore(wrap,grid.children[4]||null);
 wrap.querySelectorAll('[data-adv]').forEach(b=>b.onclick=()=>{const k=window.D?.latest?.early_event?.event_key||'';const r=prompt('Manual interpretation / reason (optional):','')??'';fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:b.dataset.adv,reason:r,event_key:k})}).then(()=>window.poll&&window.poll());});
 const st=document.createElement('style');st.textContent=`.advhero{display:flex;justify-content:space-between;gap:12px;padding:14px;border:1px solid #3a4f7c;border-radius:15px;background:linear-gradient(135deg,#14203a,#0d1525);box-shadow:0 8px 30px #0005}.advtag{font-size:10px;font-weight:900;letter-spacing:1px;color:#ffd166}.advtitle{font-size:23px;font-weight:950;margin:5px 0}.advscore{font-size:38px;font-weight:950;align-self:center}.advwhy{padding:10px 12px;margin-top:7px;background:#0c1526;border-radius:10px;color:#b9c5da;font-size:11px}.advgrid{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin-top:7px}.advmetric{background:#101a2c;border:1px solid #293955;border-radius:11px;padding:10px;text-align:center}.advmetric b{display:block;font-size:19px}.advmetric span{font-size:9px;color:#91a0ba}.livefeed{display:grid;gap:6px;max-height:330px;overflow:auto}.liveitem{display:grid;grid-template-columns:1fr auto;gap:8px;padding:10px;background:#0d1729;border:1px solid #263753;border-radius:10px}.liveitem b{font-size:13px}.liveitem .lat{font-weight:900;font-size:15px}.liveitem small{display:block;color:#91a0ba;margin-top:3px}.hot{border-color:#8a6230;box-shadow:0 0 0 1px #8a623033}.catchfast{color:#55e38a}.catchmid{color:#ffd166}.catchlate{color:#ff6879}@media(max-width:560px){.advtitle{font-size:18px}.advscore{font-size:30px}.advgrid{grid-template-columns:repeat(2,1fr)}}`;document.head.appendChild(st);
}
function renderAdvanced(){
 inject(); const d=window.D||{}; const es=(d.recent&&d.recent.early_events)||[]; const now=Date.now();
 const active=es.filter(e=>{const l=latency(e.observed_ts);return l!=null&&l<=60;});
 const scored=es.filter(e=>Number(e.score||0)>=80); const hv=scored[0]||es[0];
 q('liveSurges').textContent=active.length; q('hvCount').textContent=scored.length;
 if(hv){const side=(hv.option_type||'').toUpperCase();q('hvTitle').textContent=`${hv.symbol||'—'} ${hv.strike||'—'} ${side} • LTP ₹${Number(hv.ltp||0).toFixed(2)}`;q('hvMeta').textContent=`Score ${hv.score??'—'} • 1m ${pct(hv.move_1m_pct)} • 3m ${pct(hv.move_3m_pct)} • 5m ${pct(hv.move_5m_pct)} • ${age(hv.observed_ts)}`;q('hvScore').textContent=hv.score??'—';q('hvWhy').textContent=`High-value evidence: momentum ${pct(hv.move_1m_pct)} / ${pct(hv.move_3m_pct)} / ${pct(hv.move_5m_pct)}, volume ${Number(hv.volume_ratio||0).toFixed(2)}x, spread ${pct(hv.spread_pct)}. Status remains evidence-only until automated gates pass.`;}
 const ls=es.map(e=>latency(e.observed_ts)).filter(x=>x!=null&&x>=0); if(ls.length){q('avgCatch').textContent=(ls.reduce((a,b)=>a+b,0)/ls.length).toFixed(1)+'s';q('bestCatch').textContent=Math.min(...ls).toFixed(1)+'s';}
 q('surgeClock').textContent='• refresh 2s';
 q('liveFeed').innerHTML=active.slice(0,15).map(e=>{const l=latency(e.observed_ts)||0;const cls=l<3?'catchfast':l<10?'catchmid':'catchlate';return `<div class="liveitem ${Number(e.score||0)>=80?'hot':''}"><div><b>⚡ ${esc(e.symbol)} ${esc(e.strike)} ${esc(e.option_type)}</b><small>₹${Number(e.ltp||0).toFixed(2)} • Score ${esc(e.score)} • 1m ${pct(e.move_1m_pct)} • 3m ${pct(e.move_3m_pct)} • Vol ${Number(e.volume_ratio||0).toFixed(2)}x</small><small>${esc(age(e.observed_ts))} • Event ${esc(e.event_key||e.id)}</small></div><div class="lat ${cls}">${l.toFixed(1)}s</div></div>`}).join('')||'<div class="event">No surge event observed in the last 60 seconds. The panel will populate automatically during live observation.</div>';
}
const old=window.render; window.render=function(d){window.D=d; if(old)old(d); renderAdvanced();}; const oldPoll=window.poll; window.poll=async function(){const r=await fetch('/api/state',{cache:'no-store'});const d=await r.json();window.D=d;window.render(d);}; setInterval(()=>{try{renderAdvanced()}catch(e){}},2000); if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();
