(()=>{'use strict';
const esc=v=>String(v??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const n=(v,d=1)=>Number.isFinite(Number(v))?Number(v).toFixed(d):'—';
const card=(a,b,c='')=>`<div class="slcard"><span>${esc(a)}</span><b>${esc(b)}</b><small>${esc(c)}</small></div>`;
function table(rows,cols){if(!rows?.length)return '<div class="slmuted">No completed evidence yet.</div>';return `<div class="sltable"><div class="sltr slhead">${cols.map(c=>`<span>${esc(c[1])}</span>`).join('')}</div>${rows.slice(0,12).map(r=>`<div class="sltr">${cols.map(c=>`<span>${esc(r[c[0]]??'—')}</span>`).join('')}</div>`).join('')}</div>`}
function inject(){if(document.getElementById('strategyLab'))return;const g=document.querySelector('.grid');if(!g)return;const x=document.createElement('div');x.id='strategyLab';x.className='card full';x.innerHTML=`<style>#strategyLab{background:#0b1526;border-color:#3b5277}.slhead{font-size:18px;font-weight:950}.slsub{color:#91a0ba;font-size:10px;margin:3px 0 10px}.slguard{padding:8px;border:1px solid #2b7652;border-radius:9px;background:#0d2119;color:#a8e4c1;font-size:10px;margin-bottom:9px}.sltabs{display:grid;grid-template-columns:repeat(7,1fr);gap:5px}.sltabs button{background:#101d32;color:#eef;border:1px solid #304565;border-radius:9px;padding:8px 4px;font-size:9px;font-weight:800;cursor:pointer}.sltabs button.on{border-color:#7796ff;background:#172747}.slbody{margin-top:8px;background:#0e192b;border:1px solid #263957;border-radius:11px;padding:10px}.slcards{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.slcard{background:#111f34;border:1px solid #293d5d;border-radius:9px;padding:8px}.slcard span,.slcard small{display:block;color:#91a0ba;font-size:8px}.slcard b{display:block;font-size:15px;margin:3px 0}.slmuted{color:#91a0ba;font-size:10px;line-height:1.5}.sltable{margin-top:8px;border:1px solid #293d5d;border-radius:8px;overflow:auto}.sltr{display:grid;grid-template-columns:repeat(4,minmax(90px,1fr));gap:4px;padding:6px 7px;border-top:1px solid #1d2b42;font-size:9px}.sltr:first-child{border-top:0}.sltr span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.slhead{border-top:0;color:#91a0ba;background:#0b1627}.slnote{font-size:9px;color:#aab6ce;margin-top:8px;line-height:1.5}@media(max-width:700px){.sltabs{grid-template-columns:repeat(4,1fr)}.slcards{grid-template-columns:repeat(2,1fr)}}@media(max-width:430px){.sltabs{grid-template-columns:repeat(2,1fr)}}</style><div class="slhead">🧪 PEREZ-AI STRATEGY PERFORMANCE LAB</div><div class="slsub">Seven evidence panels • paper analytics only • no strategy or risk control is changed</div><div class="slguard">🔒 SAFETY: PAPER_MODE / ORDERS_ENABLED / risk gates remain authoritative. Analytics cannot create, modify, or force a trade.</div><div class="sltabs" id="slTabs"></div><div class="slbody" id="slBody">Loading evidence…</div>`;g.appendChild(x);load();}
const tabs=[['ENTRY','🎯 Entry Quality'],['TIMING','⏱ Timing'],['LOSS','📉 Loss Analysis'],['MFE','📐 MFE / MAE'],['REGIME','🌐 Regime'],['CEPE','⚖ CE / PE'],['COUNTER','🔬 Counterfactual']];
let data=null;
function render(k){const b=document.getElementById('slBody');if(!data){b.innerHTML='<div class="slmuted">Waiting for analytics data.</div>';return}document.querySelectorAll('#slTabs button').forEach(x=>x.classList.toggle('on',x.dataset.k===k));let h='';
if(k==='ENTRY'){const x=data.entry_quality||{};h=`<div class="slcards">${card('STATUS',x.status)}${card('SAMPLES',x.samples)}${card('WIN RATE',x.win_rate_pct==null?'—':n(x.win_rate_pct)+'%')}${card('AVG P&L',x.avg_pnl==null?'—':'₹'+n(x.avg_pnl,2))}</div><div class="slnote">Entry quality is evidence from completed paper trades. It does not replace the existing signal or risk gates.</div>`}
if(k==='TIMING'){const x=data.timing||{};h=`<div class="slcards">${card('PROOF',x.status)}${card('SAMPLES',x.samples)}${card('MINIMUM',x.minimum_samples)}${card('WINDOWS',x.windows?.filter(z=>z.samples>=5).length||0,'≥5 samples each')}</div>${table(x.windows,[['window','Window'],['samples','Trades'],['wins','Wins'],['win_rate_pct','Win %'],['net_pnl','Net P&L']])}`}
if(k==='LOSS'){const x=data.loss_analysis||{};const rows=Object.entries(x.by_exit_reason||{}).map(([reason,v])=>({reason,...v}));h=`<div class="slcards">${card('LOSSES',x.losses||0)}${card('NET LOSS','₹'+n(x.net_loss,2))}${card('TOP REASON',rows[0]?.reason||'—')}${card('REASONS',rows.length)}</div>${table(rows,[['reason','Exit reason'],['count','Count'],['net_pnl','Net P&L']])}`}
if(k==='MFE'){const x=data.mfe_mae||{};h=`<div class="slcards">${card('STATUS',x.status)}${card('SAMPLES',x.samples||0)}${card('AVG MFE',x.avg_mfe==null?'—':n(x.avg_mfe,2))}${card('AVG MAE',x.avg_mae==null?'—':n(x.avg_mae,2))}</div><div class="slnote">If unavailable, the next telemetry upgrade should capture post-entry favorable/adverse excursion before any stop/target change is considered.</div>`}
if(k==='REGIME'){h=table(data.regime||[],[['regime','Regime'],['samples','Trades'],['win_rate_pct','Win %'],['net_pnl','Net P&L']])}
if(k==='CEPE'){const x=data.ce_pe||{};h=`<div class="slcards">${card('CE SAMPLES',x.CE?.samples||0)}${card('CE WIN %',x.CE?.win_rate_pct==null?'—':n(x.CE.win_rate_pct)+'%')}${card('PE SAMPLES',x.PE?.samples||0)}${card('PE WIN %',x.PE?.win_rate_pct==null?'—':n(x.PE.win_rate_pct)+'%')}</div><div class="slnote">CE/PE comparison is descriptive only; it cannot force direction.</div>`}
if(k==='COUNTER'){h=`<div class="slcards">${card('STATUS',data.counterfactual?.status||'OBSERVATION_ONLY')}${card('ORDERS','NONE')}${card('RISK','UNCHANGED')}${card('PAPER','ONLY')}</div><div class="slnote">Counterfactual analysis may compare what happened after an observed event, but it never creates a synthetic order or rewrites historical outcomes.</div>`}
b.innerHTML=h;}
async function load(){try{const r=await fetch('/api/strategy-lab',{cache:'no-store'});data=await r.json();document.getElementById('slTabs').innerHTML=tabs.map(t=>`<button data-k="${t[0]}">${t[1]}</button>`).join('');document.querySelectorAll('#slTabs button').forEach(x=>x.onclick=()=>render(x.dataset.k));render('ENTRY')}catch(e){document.getElementById('slBody').innerHTML='<div class="slmuted">Strategy Lab temporarily unavailable. Core trading pipeline is unaffected.</div>'}}
window.addEventListener('DOMContentLoaded',inject);if(document.readyState!=='loading')inject();
})();